name: qa

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base
    steps:
      - uses: actions/checkout@v4

      - name: Install rosdeps
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src -y --ignore-src --rosdistro humble

      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
